# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_auto_20191014_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='male', max_length=30),
        ),
    ]
