# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0003_auto_20191015_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
